### PR TITLE
Tweaking `simple-import-sort` groupings

### PR DESCRIPTION
**Pull request by maranomynet**
Tweaking import sorting ... and some doc fixes.

**Changelog:**
- Tweak import sorting:
  - feat: define `^~/` and `^@/` as separate import groups (`^@/` coming first)
  - feat: group `*.styles` imports together with `*.s?css`
  - feat: Add `^views/`, `^libs?/` and `^api/` to locally aliased folder list
  - fix: Support optional file extensions on css/styles import paths
  - feat: Place css/styles imports at the bottom

Additionally: More graceful placement of the "remainders/discard" group, above the relative ../ ./ import groups.

I'd then like to release this as v8.1.0

### CODE REVIEW

**Comment by maranomynet** [comment]
I noticed we're spending quite an effort to group un-prefixed folder alliases such as `components/*` and `containers/*`

...while not addressing the more common patterns of `@/components/*` and `~/components/*`

BTW, for the next major version I'd suggest we completely drop support for the unprexfixed import special-casing, just to keep things a little "less magical" and easier to reason about.  (would that make sense to yous?)

Also, for people using vanlla-extract and styled-jsx, it's common to use the naming pattern `MyComponent.styles.ts` so it makes sense to treat those imports same as we do with `MyComponent.css.ts` or `MyComponent.module.scss`.

**Comment by maranomynet** [comment]
Current sorting:

```js
import React from 'react';
import { Alert } from '@some/ui-lib/Alert';
import { TextButton } from '@some/ui-lib/TextButton';
import { useRouter } from 'next/router';
import { ParsedUrlQuery } from 'querystring';

import { ItemList } from 'components/ItemList'; // "magic local folders" group

import FooWrapper from '../FooWrapper';

import AppointmentForm from './AppointmentForm';
import styles from './AppointmentForm.styles'; // should be with miscUtils.css

import miscStyles from '../miscUtils.css'; // should be the bottom-most group

import { isOldAppointment } from '@/shared/appointment'; // Default "discard pile" group
import { downloadBase64File } from '@/utils/file';
import { Bar } from '-dash-prefixed/lib';
import { ApplicantDetails } from '~/appointment/components';
import { useApptmtQuery } from '~/appointment/react-query/useApptmtQuery';
import { Foo } from '$/silly-import-prefix';
```

After this change:
```js
import React from 'react';
import { Alert } from '@some/ui-lib/Alert';
import { TextButton } from '@some/ui-lib/TextButton';
import { useRouter } from 'next/router';
import { ParsedUrlQuery } from 'querystring';

import { isOldAppointment } from '@/shared/appointment'; // New group: @/* 
import { downloadBase64File } from '@/utils/file';

import { ApplicantDetails } from '~/appointment/components'; // New group: ~/*
import { useApptmtQuery } from '~/appointment/react-query/useApptmtQuery';

import { ItemList } from 'components/ItemList'; // "magic local folders" group

import { Bar } from '-dash-prefixed/lib'; // New group: "all remaining non-relative" imports
import { Foo } from '$/silly-import-prefix';

import FooWrapper from '../FooWrapper';

import AppointmentForm from './AppointmentForm';

import miscStyles from '../miscUtils.css'; // All style imports happily snuggling at the bottom
import styles from './AppointmentForm.styles';
```

**Comment by maranomynet** [comment]
@Valur are ye doing much importing of *.png or *.jpeg files, or other such magical imports that we might want to group below the css/styles?

**Comment by Valur** [comment]
> 

No, haven't seen those kind of imports in any of our projects in a long time.

**Comment by maranomynet** [comment]
@Valur Good to know.
then let's wait and only add handling of those once (if ever) it starts to seem useful.

What about those other changes? Something you'd like to add?

BTW, the `@/*` magic import paths are configured by default in new `npm create next-app` projects.

**Comment by Valur** [comment]
Nothing I can think of.
This LGTM

**Pull request merged**
